[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
exclude = ["tests", "example"]
strict = true
strict_optional = true
warn_return_any = true
warn_no_return = true
disallow_untyped_defs = true
show_error_context = true
ignore_missing_imports = true
warn_unused_configs = true
warn_unused_ignores = true
plugins=["pydantic.mypy","numpy.typing.mypy_plugin"]