name: AutoFormatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt

      - name: Updating README files
        run: |
          sh scripts/update-readme.sh
          sh scripts/auto-commit.sh "Updating README files"

      - name: Code formatting and committing changes
        run: |
          sh scripts/auto-format-commit.sh
          sh scripts/auto-commit.sh "Automated formatting changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
