name: AutoUpdateFormatting
on:
  push:
    branches:
      - master

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt


      - name: Updating README files
        id: update_readme
        run: |
          bash scripts/update-readme.sh
          bash scripts/auto-commit.sh "Updating README files"
        continue-on-error: true

      - name: Code formatting and committing changes
        id: code_format
        run: |
          bash scripts/auto-format.sh
          bash scripts/auto-commit.sh "Automated formatting changes"
        continue-on-error: true

      - name: Push changes
        if: ${{ steps.update_readme.outcome == 'success' || steps.code_format.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
