name: AutoFormatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements_ci.txt

      - name: Code formatting and committing changes
        run: |
          sh scripts/auto-format-commit.sh
