name: AutoFormattingTEST

on:
  push:
    branches:
      - bugfix/auto-versioning-workflow-with-pat

jobs:
  code-formatting-TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.FINQUANT_TEST_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt

      - name: Updating README files
        id: update_readme
        run: |
          bash scripts/update_readme.sh
          bash scripts/auto_commit.sh "Updating README files"
        continue-on-error: true

      - name: Code formatting and committing changes
        id: code_format
        run: |
          bash scripts/auto_format.sh
          bash scripts/auto_commit.sh "Automated formatting changes"
        continue-on-error: true

      - name: Push changes
        if: ${{ steps.update_readme.outcome == 'success' || steps.code_format.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FINQUANT_TEST_PAT }}
          branch: ${{ github.head_ref }}
