name: Python CI

env:
  QUANDLAPIKEY: ${{ secrets.QUANDLAPIKEY }}

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run tests
        run: make test

      - name: Analysing the code with pylint
        if: ${{ matrix.python-version }} == '3.10'
        run: |
          pylint --fail-under=9 $(git ls-files '*.py')