name: Python CI

env:
  QUANDLAPIKEY: ${{ secrets.QUANDLAPIKEY }}

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run tests
        id: tests
        run: make test
        continue-on-error: true

      - name: Pylint analysis
        id: pylint_analysis
        run: |
          python -m pylint --fail-under=10 $(git ls-files '*.py')
        continue-on-error: true

      - name: mypy analysis
        id: mypy_analysis
        run: |
          python -m mypy *.py finquant
        continue-on-error: true

      - name: Check for Failures
        run: |
          if [[ "${{ steps.tests.outcome }}" != "success" || "${{ steps.pylint_analysis.outcome }}" != "success" || "${{ steps.mypy_analysis.outcome }}" != "success" ]]; then
            echo "Pipeline failed due to errors in the following steps:"
            echo "Tests: ${{ steps.tests.outcome }}"
            echo "Pylint: ${{ steps.pylint_analysis.outcome }}"
            echo "mypy: ${{ steps.mypy_analysis.outcome }}"
            exit 1
          fi